version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install pytest boto3 moto
  build:
    commands:
      - echo "Running tests..."
      - pytest tests/
